<?php

namespace App\Services;

use Config\Database;

class MasterExportService
{
    /**
     * Export master data in the official import format.
     *
     * The Data Import sheet can be uploaded again without renaming headers,
     * while the guide, examples, references, formatting, and validations are
     * generated by the same service used by Import Master Data.
     */
    public static function exportExcel(string $entity, array $filters = []): string
    {
        $entity = strtoupper($entity);
        if (!in_array($entity, MasterImportService::SUPPORTED_TYPES, true)) {
            throw new \InvalidArgumentException('Entity export tidak dikenali.');
        }

        $rows = match ($entity) {
            'TEACHERS'     => self::teacherRows($filters),
            'SUBJECTS'     => self::subjectRows($filters),
            'GRADE_LEVELS' => self::gradeLevelRows($filters),
            'CLASSROOMS'   => self::classroomRows($filters),
            'ROOMS'        => self::roomRows($filters),
            'STUDENTS'     => self::studentRows($filters),
        };

        $filename = 'master_' . strtolower($entity) . '_' . date('Ymd_His') . '.xlsx';
        $filePath = MasterImportService::generateDataWorkbook($entity, $rows, $filename);

        AuditService::log(
            'master_export',
            'EXPORT_EXCEL',
            $entity,
            null,
            null,
            ['filename' => $filename, 'rows' => count($rows), 'import_compatible' => true],
            'Export master data in official import-compatible Excel format'
        );

        return $filePath;
    }

    /** @return array<int, array<string, mixed>> */
    private static function teacherRows(array $filters): array
    {
        $teachers = TeacherService::getTeachers($filters, 10000)['data'];
        $unitCodes = self::idCodeMap('school_units');

        return array_map(static function (array $teacher) use ($unitCodes): array {
            $assignments = $teacher['assignments'] ?? [];
            $primaryUnit = $unitCodes[(int) ($teacher['primary_unit_id'] ?? 0)] ?? '';
            $additionalUnits = [];
            foreach ($assignments as $assignment) {
                $code = $assignment['unit_code'] ?? ($unitCodes[(int) ($assignment['unit_id'] ?? 0)] ?? '');
                if ($code === '') {
                    continue;
                }
                if ((int) ($assignment['is_primary'] ?? 0) === 1) {
                    $primaryUnit = $code;
                } elseif ($code !== $primaryUnit) {
                    $additionalUnits[] = $code;
                }
            }

            return [
                'employee_number'  => $teacher['employee_number'] ?? '',
                'nip'              => $teacher['nip'] ?? '',
                'nik'              => $teacher['nik'] ?? '',
                'full_name'        => $teacher['full_name'] ?? '',
                'title_prefix'     => $teacher['title_prefix'] ?? '',
                'degree_suffix'    => $teacher['degree_suffix'] ?? '',
                'gender'           => $teacher['gender'] ?? '',
                'birth_place'      => $teacher['birth_place'] ?? '',
                'birth_date'       => $teacher['birth_date'] ?? '',
                'phone'            => $teacher['phone'] ?? '',
                'email'            => $teacher['email'] ?? '',
                'address'          => $teacher['address'] ?? '',
                'employment_status'=> $teacher['employment_status'] ?? '',
                'employment_type'  => $teacher['employment_type'] ?? '',
                'primary_unit'     => $primaryUnit,
                'additional_units' => implode(',', array_values(array_unique($additionalUnits))),
                'hire_date'        => $teacher['hire_date'] ?? '',
                'notes'            => $teacher['notes'] ?? '',
                'active'           => (string) ((int) ($teacher['is_active'] ?? 1)),
            ];
        }, $teachers);
    }

    /** @return array<int, array<string, mixed>> */
    private static function subjectRows(array $filters): array
    {
        $subjects = SubjectService::getSubjects($filters, 10000)['data'];
        $roomTypeCodes = self::idCodeMap('room_types');

        return array_map(static function (array $subject) use ($roomTypeCodes): array {
            $units = [];
            foreach ($subject['unit_availabilities'] ?? [] as $availability) {
                if ((int) ($availability['is_available'] ?? 1) === 1 && !empty($availability['unit_code'])) {
                    $units[] = $availability['unit_code'];
                }
            }
            $aliases = [];
            foreach ($subject['aliases'] ?? [] as $alias) {
                $value = trim((string) ($alias['alias_name'] ?? $alias['alias_code'] ?? ''));
                if ($value !== '') {
                    $aliases[] = $value;
                }
            }

            return [
                'code'                    => $subject['code'] ?? '',
                'name'                    => $subject['name'] ?? '',
                'short_name'              => $subject['short_name'] ?? '',
                'category'                => $subject['category'] ?? '',
                'counts_in_report'        => (string) ((int) ($subject['counts_in_report'] ?? 1)),
                'counts_as_teaching_load' => (string) ((int) ($subject['counts_as_teaching_load'] ?? 1)),
                'units'                   => implode(',', array_values(array_unique($units))),
                'aliases'                 => implode(';', array_values(array_unique($aliases))),
                'default_room_type'       => $roomTypeCodes[(int) ($subject['default_room_type_id'] ?? 0)] ?? '',
                'sort_order'              => (string) ((int) ($subject['sort_order'] ?? 0)),
                'active'                  => (string) ((int) ($subject['is_active'] ?? 1)),
            ];
        }, $subjects);
    }

    /** @return array<int, array<string, mixed>> */
    private static function gradeLevelRows(array $filters): array
    {
        $unitId = !empty($filters['unit_id']) ? (int) $filters['unit_id'] : null;
        $unitIds = array_map('intval', $filters['unit_ids'] ?? UnitScopeService::accessibleUnitIds());
        $gradeLevels = GradeLevelService::getGradeLevels($unitId, $unitIds);

        return array_map(static fn (array $grade): array => [
            'unit'         => $grade['unit_code'] ?? '',
            'grade_number' => (string) ((int) ($grade['grade_number'] ?? 0)),
            'code'         => $grade['code'] ?? '',
            'name'         => $grade['name'] ?? '',
            'phase'        => $grade['phase'] ?? '',
            'sort_order'   => (string) ((int) ($grade['sort_order'] ?? 0)),
            'active'       => (string) ((int) ($grade['is_active'] ?? 1)),
        ], $gradeLevels);
    }

    /** @return array<int, array<string, mixed>> */
    private static function classroomRows(array $filters): array
    {
        $classrooms = ClassroomService::getClassrooms($filters, 10000)['data'];
        $db = Database::connect();
        $periodRows = $db->table('academic_periods')
            ->select('academic_periods.id, academic_periods.semester_number, academic_years.name AS academic_year')
            ->join('academic_years', 'academic_years.id = academic_periods.academic_year_id')
            ->get()->getResultArray();
        $periods = [];
        foreach ($periodRows as $period) {
            $periods[(int) $period['id']] = $period;
        }
        $teacherRows = $db->table('teachers')
            ->select('id, employee_number, nip, nik')
            ->where('deleted_at IS NULL')
            ->get()->getResultArray();
        $teacherIdentifiers = [];
        foreach ($teacherRows as $teacher) {
            $teacherIdentifiers[(int) $teacher['id']] =
                $teacher['employee_number'] ?: ($teacher['nip'] ?: ($teacher['nik'] ?: ''));
        }

        return array_map(static function (array $classroom) use ($periods, $teacherIdentifiers): array {
            $period = $periods[(int) ($classroom['academic_period_id'] ?? 0)] ?? [];
            return [
                'academic_year'               => $period['academic_year'] ?? '',
                'semester'                    => isset($period['semester_number']) ? (string) $period['semester_number'] : '',
                'unit'                        => $classroom['unit_code'] ?? '',
                'grade'                       => $classroom['grade_code'] ?? '',
                'code'                        => $classroom['code'] ?? '',
                'name'                        => $classroom['name'] ?? '',
                'major'                       => $classroom['major'] ?? '',
                'specialization'              => $classroom['specialization'] ?? '',
                'capacity'                    => $classroom['capacity'] === null ? '' : (string) $classroom['capacity'],
                'homeroom_teacher_identifier' => $teacherIdentifiers[(int) ($classroom['homeroom_teacher_id'] ?? 0)] ?? '',
                'default_room_code'            => $classroom['room_code'] ?? '',
                'active'                       => (string) ((int) ($classroom['is_active'] ?? 1)),
            ];
        }, $classrooms);
    }

    /** @return array<int, array<string, mixed>> */
    private static function roomRows(array $filters): array
    {
        $rooms = RoomService::getRooms($filters, 10000)['data'];

        return array_map(static function (array $room): array {
            $facilities = json_decode((string) ($room['facilities_json'] ?? ''), true);
            return [
                'code'                 => $room['code'] ?? '',
                'name'                 => $room['name'] ?? '',
                'room_type'            => $room['room_type_code'] ?? '',
                'unit'                 => $room['unit_code'] ?? '',
                'shared_between_units' => (string) ((int) ($room['shared_between_units'] ?? 0)),
                'capacity'             => $room['capacity'] === null ? '' : (string) $room['capacity'],
                'location'             => $room['location'] ?? '',
                'floor'                => $room['floor'] ?? '',
                'facilities'           => is_array($facilities) ? implode(',', $facilities) : '',
                'active'               => (string) ((int) ($room['is_active'] ?? 1)),
            ];
        }, $rooms);
    }

    private static function studentRows(array $filters): array
    {
        $db = Database::connect();
        $builder = $db->table('elective_students es')
            ->select('es.*, su.code AS unit_code, ay.name AS academic_year_name, c.code AS classroom_code')
            ->join('school_units su', 'su.id = es.unit_id')
            ->join('academic_years ay', 'ay.id = es.academic_year_id')
            ->join('classrooms c', 'c.id = es.classroom_id', 'left')
            ->where('es.is_active', 1)
            ->orderBy('su.code')->orderBy('es.current_grade')->orderBy('es.full_name');

        if (!empty($filters['unit_id'])) {
            $builder->where('es.unit_id', (int) $filters['unit_id']);
        }

        $students = $builder->get()->getResultArray();
        return array_map(static function (array $st): array {
            return [
                'student_number' => $st['student_number'] ?? '',
                'full_name'      => $st['full_name'] ?? '',
                'unit'           => $st['unit_code'] ?? '',
                'academic_year'  => $st['academic_year_name'] ?? '',
                'current_grade'  => (string) ($st['current_grade'] ?? ''),
                'classroom_code' => $st['classroom_code'] ?? '',
                'user_id'        => $st['user_id'] ? (string) $st['user_id'] : '',
            ];
        }, $students);
    }

    /** @return array<int, string> */
    private static function idCodeMap(string $table): array
    {
        $rows = Database::connect()->table($table)->select('id, code')->get()->getResultArray();
        $map = [];
        foreach ($rows as $row) {
            $map[(int) $row['id']] = (string) $row['code'];
        }
        return $map;
    }
}
