<?= $this->extend('layouts/admin') ?>
<?= $this->section('main_content') ?>
<?php
$labels=['regulations'=>'Regulasi','sources'=>'Sumber Kurikulum','profile'=>'Profil Lulusan','outcomes'=>'CP & Elemen','objectives'=>'Tujuan Pembelajaran','sequences'=>'ATP','coverage'=>'Coverage','packs'=>'Paket Pembelajaran','imports'=>'Import'];
$links=['regulations'=>'references/regulations','sources'=>'references/curriculum-sources','profile'=>'references/graduate-profile','outcomes'=>'curriculum/outcomes','objectives'=>'curriculum/objectives','sequences'=>'curriculum/sequences','coverage'=>'curriculum/coverage','packs'=>'curriculum/learning-packs','imports'=>'curriculum/education-imports'];
?>
<div class="d-flex justify-content-between align-items-start mb-4 gap-3">
    <div><h4 class="fw-bold mb-1"><i data-lucide="network" class="text-primary me-2"></i>IALOS Education</h4><p class="text-muted mb-0">Satu ruang kerja terpadu untuk referensi resmi, adaptasi sekolah dan guru, CP → TP → ATP, coverage, serta paket pembelajaran.</p></div>
    <span class="badge text-bg-primary rounded-pill px-3 py-2">Phase 1</span>
</div>
<div class="card border-0 shadow-sm rounded-4 mb-4"><div class="card-body p-2"><nav class="nav nav-pills gap-1 flex-wrap">
<?php foreach($links as $key=>$href): ?><a class="nav-link <?= $section===$key?'active':'' ?>" href="<?= base_url($href) ?>"><?= esc($labels[$key]) ?></a><?php endforeach ?>
</nav></div></div>

<?php if(session('error')): ?><div class="alert alert-danger"><?= esc(session('error')) ?></div><?php endif ?>
<?php if(session('success')): ?><div class="alert alert-success"><?= esc(session('success')) ?></div><?php endif ?>

<?php if($section==='regulations' && has_permission('regulations.manage')): ?>
<details class="card border-0 shadow-sm rounded-4 mb-4"><summary class="card-header bg-white fw-semibold p-3">Tambah regulasi</summary><div class="card-body"><form method="post" action="<?= base_url('references/regulations') ?>" class="row g-3"><?= csrf_field() ?>
<div class="col-md-2"><input class="form-control" name="code" placeholder="Kode" required></div><div class="col-md-4"><input class="form-control" name="title" placeholder="Judul" required></div><div class="col-md-3"><input class="form-control" name="authority" placeholder="Otoritas" required></div><div class="col-md-2"><input class="form-control" name="regulation_type" placeholder="Jenis" required></div><div class="col-md-1"><button class="btn btn-primary w-100">Simpan</button></div>
</form></div></details>
<?php elseif($section==='sources' && has_permission('curriculum_sources.manage')): ?>
<details class="card border-0 shadow-sm rounded-4 mb-4"><summary class="card-header bg-white fw-semibold p-3">Tambah sumber resmi</summary><div class="card-body"><form method="post" action="<?= base_url('references/curriculum-sources') ?>" class="row g-3"><?= csrf_field() ?>
<div class="col-md-2"><input class="form-control" name="code" placeholder="Kode" required></div><div class="col-md-4"><input class="form-control" name="title" placeholder="Judul sumber" required></div><div class="col-md-2"><input class="form-control" name="source_type" placeholder="Jenis" required></div><div class="col-md-3"><input class="form-control" name="issuer" placeholder="Penerbit" required></div><div class="col-md-1"><button class="btn btn-primary w-100">Simpan</button></div>
</form></div></details>
<?php elseif($section==='outcomes' && has_permission('learning_outcomes.manage')): ?>
<details class="card border-0 shadow-sm rounded-4 mb-4"><summary class="card-header bg-white fw-semibold p-3">Tambah capaian pembelajaran</summary><div class="card-body"><form method="post" action="<?= base_url('curriculum/outcomes') ?>" class="row g-3"><?= csrf_field() ?>
<div class="col-md-3"><select class="form-select" name="curriculum_version_id" required><option value="">Versi kurikulum</option><?php foreach($versions as $v): ?><option value="<?= $v['id'] ?>"><?= esc($v['code'].' — '.$v['name']) ?></option><?php endforeach ?></select></div>
<div class="col-md-3"><select class="form-select" name="subject_id" required><option value="">Mata pelajaran</option><?php foreach($subjects as $s): ?><option value="<?= $s['id'] ?>"><?= esc($s['name']) ?></option><?php endforeach ?></select></div>
<div class="col-md-2"><select class="form-select" name="grade_level_id" required><option value="">Tingkat</option><?php foreach($gradeLevels as $g): ?><option value="<?= $g['id'] ?>"><?= esc($g['name']) ?></option><?php endforeach ?></select></div>
<div class="col-md-2"><input class="form-control" name="code" placeholder="Kode CP" required></div><div class="col-md-2"><input class="form-control" name="phase" placeholder="Fase" required></div><div class="col-12"><textarea class="form-control" name="statement" placeholder="Pernyataan CP" required></textarea></div><div class="col-12 text-end"><button class="btn btn-primary">Simpan CP</button></div>
</form></div></details>
<?php elseif($section==='objectives' && has_permission('learning_objectives.manage')): ?>
<div class="alert alert-info border-0">TP nasional dibuat dari sumber resmi. Adaptasi sekolah/guru dibuat dari aksi pada TP induk sehingga lineage tidak terputus.</div>
<?php if(has_permission('regulations.manage')): ?><details class="card border-0 shadow-sm rounded-4 mb-4"><summary class="card-header bg-white fw-semibold p-3">Tambah TP nasional</summary><div class="card-body"><form method="post" action="<?= base_url('curriculum/objectives') ?>" class="row g-3"><?= csrf_field() ?><input type="hidden" name="source_level" value="NATIONAL"><div class="col-md-4"><select class="form-select" name="learning_outcome_id" required><option value="">Pilih CP</option><?php foreach($outcomeOptions as $cp): ?><option value="<?= $cp['id'] ?>"><?= esc($cp['code']) ?></option><?php endforeach ?></select></div><div class="col-md-2"><input class="form-control" name="code" placeholder="Kode TP" required></div><div class="col-md-5"><input class="form-control" name="statement" placeholder="Pernyataan TP" required></div><div class="col-md-1"><button class="btn btn-primary w-100">Simpan</button></div></form></div></details><?php endif ?>
<?php elseif($section==='sequences' && has_permission('learning_sequences.manage')): ?>
<details class="card border-0 shadow-sm rounded-4 mb-4"><summary class="card-header bg-white fw-semibold p-3">Buat ATP</summary><div class="card-body"><form method="post" action="<?= base_url('curriculum/sequences') ?>" class="row g-3"><?= csrf_field() ?>
<div class="col-md-3"><select class="form-select" name="curriculum_version_id" required><option value="">Versi</option><?php foreach($versions as $v): ?><option value="<?= $v['id'] ?>"><?= esc($v['code']) ?></option><?php endforeach ?></select></div><div class="col-md-2"><select class="form-select" name="unit_id" required><option value="">Unit</option><?php foreach($units as $u): ?><option value="<?= $u['id'] ?>"><?= esc($u['name']) ?></option><?php endforeach ?></select></div><div class="col-md-2"><select class="form-select" name="subject_id" required><option value="">Mapel</option><?php foreach($subjects as $s): ?><option value="<?= $s['id'] ?>"><?= esc($s['name']) ?></option><?php endforeach ?></select></div><div class="col-md-2"><select class="form-select" name="grade_level_id" required><option value="">Tingkat</option><?php foreach($gradeLevels as $g): ?><option value="<?= $g['id'] ?>"><?= esc($g['name']) ?></option><?php endforeach ?></select></div><div class="col-md-1"><input class="form-control" name="phase" placeholder="Fase" required></div><div class="col-md-2"><input class="form-control" name="code" placeholder="Kode" required></div><div class="col-10"><input class="form-control" name="name" placeholder="Nama ATP" required></div><div class="col-2"><button class="btn btn-primary w-100">Buat ATP</button></div>
</form></div></details>
<?php elseif($section==='packs' && has_permission('learning_packs.manage')): ?>
<details class="card border-0 shadow-sm rounded-4 mb-4"><summary class="card-header bg-white fw-semibold p-3">Buat paket pembelajaran</summary><div class="card-body"><form method="post" action="<?= base_url('curriculum/learning-packs') ?>" class="row g-3"><?= csrf_field() ?>
<div class="col-md-3"><select class="form-select" name="curriculum_version_id" required><option value="">Versi</option><?php foreach($versions as $v): ?><option value="<?= $v['id'] ?>"><?= esc($v['code']) ?></option><?php endforeach ?></select></div><div class="col-md-2"><select class="form-select" name="unit_id" required><option value="">Unit</option><?php foreach($units as $u): ?><option value="<?= $u['id'] ?>"><?= esc($u['name']) ?></option><?php endforeach ?></select></div><div class="col-md-2"><select class="form-select" name="subject_id" required><option value="">Mapel</option><?php foreach($subjects as $s): ?><option value="<?= $s['id'] ?>"><?= esc($s['name']) ?></option><?php endforeach ?></select></div><div class="col-md-2"><select class="form-select" name="grade_level_id" required><option value="">Tingkat</option><?php foreach($gradeLevels as $g): ?><option value="<?= $g['id'] ?>"><?= esc($g['name']) ?></option><?php endforeach ?></select></div><div class="col-md-1"><input class="form-control" name="code" placeholder="Kode" required></div><div class="col-md-2"><input class="form-control" name="name" placeholder="Nama paket" required></div><div class="col-12 text-end"><button class="btn btn-primary">Simpan</button></div>
</form></div></details>
<?php elseif($section==='coverage'): ?>
<div class="card border-0 shadow-sm rounded-4 mb-4"><div class="card-body"><form method="get" class="row g-3"><div class="col-md-3"><select class="form-select" name="curriculum_version_id" required><option value="">Versi</option><?php foreach($versions as $v): ?><option value="<?= $v['id'] ?>"><?= esc($v['code']) ?></option><?php endforeach ?></select></div><div class="col-md-2"><select class="form-select" name="unit_id" required><?php foreach($units as $u): ?><option value="<?= $u['id'] ?>"><?= esc($u['name']) ?></option><?php endforeach ?></select></div><div class="col-md-3"><select class="form-select" name="subject_id" required><option value="">Mapel</option><?php foreach($subjects as $s): ?><option value="<?= $s['id'] ?>"><?= esc($s['name']) ?></option><?php endforeach ?></select></div><div class="col-md-2"><select class="form-select" name="grade_level_id" required><option value="">Tingkat</option><?php foreach($gradeLevels as $g): ?><option value="<?= $g['id'] ?>"><?= esc($g['name']) ?></option><?php endforeach ?></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Analisis</button></div></form></div></div>
<?php elseif($section==='imports' && has_permission('learning_outcomes.manage')): ?>
<details class="card border-0 shadow-sm rounded-4 mb-4"><summary class="card-header bg-white fw-semibold p-3">Stage import JSON terkontrol</summary><div class="card-body"><form method="post" action="<?= base_url('curriculum/education-imports') ?>" class="row g-3"><?= csrf_field() ?><div class="col-md-3"><select class="form-select" name="unit_id" required><?php foreach($units as $u): ?><option value="<?= $u['id'] ?>"><?= esc($u['name']) ?></option><?php endforeach ?></select></div><div class="col-md-3"><select class="form-select" name="curriculum_version_id" required><?php foreach($versions as $v): ?><option value="<?= $v['id'] ?>"><?= esc($v['code']) ?></option><?php endforeach ?></select></div><div class="col-md-6"><input class="form-control" name="source_filename" value="education-foundation.json" required></div><div class="col-12"><textarea class="form-control font-monospace" rows="7" name="rows_json" placeholder='[{"entity_type":"CP",...}]' required></textarea></div><div class="col-12 text-end"><button class="btn btn-primary">Validasi ke staging</button></div></form></div></details>
<?php endif ?>

<div class="card border-0 shadow-sm rounded-4"><div class="card-header bg-white p-3"><h6 class="mb-0 fw-bold"><?= esc($labels[$section]) ?></h6></div><div class="card-body p-0">
<?php if($section==='coverage' && isset($rows['total_objectives'])): ?><div class="p-4"><div class="row g-3 text-center"><div class="col"><div class="fs-3 fw-bold"><?= $rows['coverage_percent'] ?>%</div><small class="text-muted">Coverage</small></div><div class="col"><div class="fs-3 fw-bold"><?= $rows['covered_objectives'] ?>/<?= $rows['total_objectives'] ?></div><small class="text-muted">TP tercakup</small></div><div class="col"><div class="fs-3 fw-bold text-danger"><?= count($rows['missing']) ?></div><small class="text-muted">Belum masuk ATP</small></div><div class="col"><div class="fs-3 fw-bold text-warning"><?= count($rows['duplicates']) ?></div><small class="text-muted">Duplikat lintas ATP</small></div></div></div>
<?php elseif(empty($rows)): ?><div class="text-center text-muted p-5"><i data-lucide="inbox" class="mb-2"></i><p class="mb-0">Belum ada data pada bagian ini.</p></div>
<?php else: ?><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="ps-4">Kode</th><th>Nama / Pernyataan</th><th>Scope / Sumber</th><th>Status</th><th class="pe-4">Detail</th></tr></thead><tbody>
<?php foreach($rows as $row): ?><tr><td class="ps-4 fw-semibold"><?= esc($row['code'] ?? $row['row_number'] ?? '-') ?></td><td><?= esc($row['title'] ?? $row['name'] ?? $row['statement'] ?? $row['source_filename'] ?? '-') ?></td><td><?= esc($row['authority'] ?? $row['issuer'] ?? $row['subject_name'] ?? $row['source_level'] ?? '-') ?></td><td><span class="badge text-bg-light"><?= esc($row['workflow_status'] ?? $row['status'] ?? (($row['is_active'] ?? false)?'ACTIVE':'INACTIVE')) ?></span></td><td class="pe-4 text-muted">
<?= esc($row['grade_name'] ?? $row['description'] ?? '') ?><?php if(!empty($row['elements'])): ?><div class="small mt-1"><?= esc(implode(' · ',array_column($row['elements'],'name'))) ?></div><?php endif ?>
<?php if($section==='outcomes' && has_permission('learning_outcomes.manage')): ?><details><summary class="small text-primary">Tambah elemen</summary><form method="post" action="<?= base_url('curriculum/outcomes/'.$row['uuid'].'/elements') ?>" class="mt-2"><?= csrf_field() ?><input class="form-control form-control-sm mb-1" name="code" placeholder="Kode" required><input class="form-control form-control-sm mb-1" name="name" placeholder="Nama elemen" required><input type="number" class="form-control form-control-sm mb-1" name="sort_order" value="1" min="1" required><button class="btn btn-sm btn-outline-primary">Tambah</button></form></details><?php endif ?>
<?php if($section==='objectives' && has_permission('learning_objectives.manage')): ?><details><summary class="small text-primary">Adaptasi / kriteria</summary><form method="post" action="<?= base_url('curriculum/objectives/'.$row['uuid'].'/adapt') ?>" class="mt-2"><?= csrf_field() ?><select class="form-select form-select-sm mb-1" name="unit_id" required><?php foreach($units as $u): ?><option value="<?= $u['id'] ?>"><?= esc($u['name']) ?></option><?php endforeach ?></select><select class="form-select form-select-sm mb-1" name="source_level"><?php if($row['source_level']==='NATIONAL'): ?><option value="SCHOOL">Sekolah</option><?php endif ?><option value="TEACHER">Guru</option></select><input class="form-control form-control-sm mb-1" name="statement" value="<?= esc($row['statement']) ?>" required><button class="btn btn-sm btn-outline-primary">Buat adaptasi</button></form><?php if($row['source_level']!=='NATIONAL' || has_permission('regulations.manage')): ?><form method="post" action="<?= base_url('curriculum/objectives/'.$row['uuid'].'/criteria') ?>" class="mt-2"><?= csrf_field() ?><input class="form-control form-control-sm mb-1" name="description" placeholder="Kriteria keberhasilan" required><input type="hidden" name="sort_order" value="1"><button class="btn btn-sm btn-outline-secondary">Tambah kriteria</button></form><?php endif ?></details><?php endif ?>
<?php if($section==='sequences' && (has_permission('learning_sequences.manage') || has_permission('learning_sequences.validate') || has_permission('learning_sequences.review') || has_permission('learning_sequences.approve') || has_permission('learning_sequences.lock'))): ?><details><summary class="small text-primary">Kelola ATP</summary>
<?php if(has_permission('learning_sequences.manage')): ?><form method="post" action="<?= base_url('curriculum/sequences/'.$row['uuid'].'/items') ?>" class="mt-2"><?= csrf_field() ?><select class="form-select form-select-sm mb-1" name="objective_uuid" required><option value="">Pilih TP</option><?php foreach($objectiveOptions as $tp): ?><option value="<?= esc($tp['uuid']) ?>"><?= esc($tp['code']) ?></option><?php endforeach ?></select><button class="btn btn-sm btn-outline-primary">Tambah TP</button></form><?php endif ?>
<form method="post" action="<?= base_url('curriculum/sequences/'.$row['uuid'].'/transition') ?>" class="mt-2"><?= csrf_field() ?><input type="hidden" name="revision_number" value="<?= (int)$row['revision_number'] ?>"><select class="form-select form-select-sm mb-1" name="target_status"><?php if(has_permission('learning_sequences.validate')): ?><option>VALIDATED</option><?php endif ?><?php if(has_permission('learning_sequences.review')): ?><option>REVIEWED</option><?php endif ?><?php if(has_permission('learning_sequences.approve')): ?><option>APPROVED</option><?php endif ?><?php if(has_permission('learning_sequences.lock')): ?><option>LOCKED</option><option>ARCHIVED</option><?php endif ?></select><button class="btn btn-sm btn-outline-success">Transisi</button></form>
<?php if(has_permission('learning_sequences.manage')): ?><form method="post" action="<?= base_url('curriculum/sequences/'.$row['uuid'].'/clone') ?>" class="mt-2"><?= csrf_field() ?><input class="form-control form-control-sm mb-1" name="code" value="<?= esc($row['code'].'-R2') ?>" required><button class="btn btn-sm btn-outline-secondary">Klon revisi</button></form><?php endif ?></details><?php endif ?>
<?php if($section==='packs' && has_permission('learning_packs.manage')): ?><details><summary class="small text-primary">Tautkan TP / ATP</summary><form method="post" action="<?= base_url('curriculum/learning-packs/'.$row['uuid'].'/objectives') ?>" class="mt-2"><?= csrf_field() ?><select class="form-select form-select-sm mb-1" name="objective_uuid" required><?php foreach($objectiveOptions as $tp): ?><option value="<?= esc($tp['uuid']) ?>"><?= esc($tp['code']) ?></option><?php endforeach ?></select><button class="btn btn-sm btn-outline-primary">Tautkan TP</button></form><form method="post" action="<?= base_url('curriculum/learning-packs/'.$row['uuid'].'/sequences') ?>" class="mt-2"><?= csrf_field() ?><select class="form-select form-select-sm mb-1" name="sequence_uuid" required><?php foreach($sequenceOptions as $atp): ?><option value="<?= esc($atp['uuid']) ?>"><?= esc($atp['code']) ?></option><?php endforeach ?></select><button class="btn btn-sm btn-outline-secondary">Tautkan ATP</button></form></details><?php endif ?>
</td></tr><?php endforeach ?>
</tbody></table></div><?php endif ?>
</div></div>
<?= $this->endSection() ?>
