<?= $this->extend('layouts/admin') ?>
<?= $this->section('main_content') ?>
<div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><h4 class="fw-bold mb-1 text-slate-800">Tahun Pelajaran</h4><p class="text-muted fs-7 mb-0">Kelola rentang tahunan sebagai wadah periode semester.</p></div><div class="d-flex gap-2"><a href="<?= base_url('academic-periods') ?>" class="btn btn-outline-secondary rounded-3">Lihat Periode</a><?php if (has_permission('academic_years.manage')): ?><a href="<?= base_url('academic-years/create') ?>" class="btn btn-primary rounded-3"><i data-lucide="plus" style="width:16px"></i> Tambah Tahun</a><?php endif; ?></div></div>
<?php if (session('success')): ?><div class="alert alert-success rounded-3"><?= esc(session('success')) ?></div><?php endif; ?>
<?php if (session('error')): ?><div class="alert alert-danger rounded-3"><?= esc(session('error')) ?></div><?php endif; ?>
<div class="card border-0 shadow-sm rounded-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2"><div class="fs-8 text-muted">Total Data: <span class="fw-bold text-dark"><?= count($years) ?></span> tahun pelajaran</div></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr class="text-uppercase text-muted fs-8 fw-bold bg-light"><th class="text-center ps-3" style="width: 55px;">No.</th><th>Tahun Pelajaran</th><th>Rentang</th><th>Durasi</th><th>Status</th><th class="text-end pe-4">Aksi</th></tr></thead><tbody>
<?php if (!$years): ?><tr><td colspan="6" class="text-center py-5"><i data-lucide="calendar-plus" class="text-muted mb-2" style="width:36px;height:36px"></i><div class="fw-semibold">Belum ada tahun pelajaran</div><div class="text-muted fs-8 mb-3">Tambahkan tahun pelajaran sebelum membuat periode semester.</div><?php if (has_permission('academic_years.manage')): ?><a class="btn btn-sm btn-primary" href="<?= base_url('academic-years/create') ?>">Tambah Sekarang</a><?php endif; ?></td></tr><?php else: foreach ($years as $idx => $year): $days=(int)floor((strtotime($year['end_date'])-strtotime($year['start_date']))/86400)+1; ?>
<tr><td class="text-center fw-semibold text-secondary fs-8 ps-3"><?= $idx + 1 ?></td><td><div class="fw-bold text-slate-800"><?= esc($year['name']) ?></div><small class="text-muted"><?= (int)$year['is_active']===1?'Sedang digunakan':'Tidak aktif' ?></small></td><td><?= date('d-m-Y',strtotime($year['start_date'])) ?> <span class="text-muted">s.d.</span> <?= date('d-m-Y',strtotime($year['end_date'])) ?></td><td><?= number_format($days) ?> hari</td><td><?php if((int)$year['is_active']===1): ?><span class="badge bg-success bg-opacity-10 text-success">AKTIF</span><?php else: ?><span class="badge bg-light text-slate-600"><?= esc($year['status']) ?></span><?php endif; ?></td><td class="text-end pe-4"><div class="d-inline-flex gap-2"><?php if(has_permission('academic_years.manage')): ?><a class="btn btn-sm btn-light" href="<?= base_url('academic-years/'.$year['uuid'].'/edit') ?>">Edit</a><?php if((int)$year['is_active']===0 && $year['status']!=='ARCHIVED'): ?><form method="POST" action="<?= base_url('academic-years/'.$year['uuid'].'/activate') ?>" data-confirm="Aktifkan tahun <?= esc($year['name']) ?>? Tahun yang sedang aktif akan dinonaktifkan." data-confirm-title="Aktifkan tahun ajaran?" data-confirm-button="Aktifkan"><?= csrf_field() ?><button class="btn btn-sm btn-outline-success">Aktifkan</button></form><?php endif; endif; ?></div></td></tr>
<?php endforeach; endif; ?></tbody></table></div></div></div>
<script>document.addEventListener('DOMContentLoaded',function(){if(typeof lucide!=='undefined')lucide.createIcons();});</script>
<?= $this->endSection() ?>
