<!doctype html><html lang="id"><head><meta charset="utf-8"><title>SK Pembagian Tugas</title>
<style>body{font:12px "Times New Roman",serif;color:#000;margin:22mm 18mm}.toolbar{position:fixed;right:18px;top:12px}.toolbar button{font:14px Arial;padding:9px 16px}.header{text-align:center;border-bottom:3px double #000;padding-bottom:10px}.header h2,.header p{margin:3px}.title{text-align:center;margin:24px 0 16px}.title h3,.title p{margin:4px}.content{line-height:1.5;text-align:justify}table{width:100%;border-collapse:collapse;margin:14px 0;font-size:10px}th,td{border:1px solid #000;padding:5px}th{text-align:center}.signature{width:42%;margin:28px 0 0 auto;line-height:1.5}.page-break{page-break-before:always}@media print{.toolbar{display:none}body{margin:0}@page{size:A4 portrait;margin:14mm}}</style></head><body>
<?php $unit=$document['unit'];$version=$document['version']; ?>
<div class="toolbar"><button onclick="window.print()">Cetak / Simpan PDF</button></div>
<div class="header"><h2><?= esc(strtoupper($unit['name'])) ?></h2><p><?= esc($unit['address'] ?: '') ?></p><p><?= esc(trim(($unit['phone'] ? 'Tel. '.$unit['phone'].' ' : '').($unit['email'] ?: ''))) ?></p></div>
<div class="title"><h3>KEPUTUSAN KEPALA SEKOLAH</h3><p>Nomor: <?= esc($document['document_number']) ?></p><h3>TENTANG</h3><p><strong>PEMBAGIAN TUGAS MENGAJAR DAN TUGAS TAMBAHAN<br>TAHUN PELAJARAN <?= esc($version['year_name']) ?> · <?= (int)$version['semester_number']===1?'SEMESTER GANJIL':'SEMESTER GENAP' ?></strong></p></div>
<div class="content"><p><strong>Menimbang:</strong> bahwa untuk menjamin kelancaran proses pembelajaran, perlu menetapkan pembagian tugas mengajar dan tugas tambahan guru.</p><p><strong>Mengingat:</strong> ketentuan peraturan pendidikan yang berlaku serta program kerja <?= esc($unit['name']) ?>.</p><p style="text-align:center"><strong>MEMUTUSKAN</strong></p><p><strong>Menetapkan:</strong> pembagian tugas guru sebagaimana tercantum pada lampiran keputusan ini. Keputusan berlaku selama periode <?= esc($version['period_name']) ?> dan dapat diperbaiki apabila terdapat kekeliruan.</p></div>
<div class="signature">Ditetapkan di: <?= esc($unit['document_city'] ?: '................') ?><br>Pada tanggal: <?= date('d-m-Y',strtotime($document['issued_date'])) ?><br><br>Kepala Sekolah,<br><br><br><strong><u><?= esc($unit['head_name'] ?: '................................') ?></u></strong><br><?= $unit['head_identifier'] ? 'NIP/Identitas: '.esc($unit['head_identifier']) : '' ?></div>
<div class="page-break"></div><h3 style="text-align:center">LAMPIRAN PEMBAGIAN TUGAS</h3><p>Nomor: <?= esc($document['document_number']) ?></p>
<table><thead><tr><th>No</th><th>Nama Guru</th><th>NIP/No. Pegawai</th><th>Mata Pelajaran & Kelas</th><th>Tugas Tambahan</th><th>JP Mengajar</th><th>Ekuivalensi</th><th>Total</th></tr></thead><tbody>
<?php foreach($document['teachers'] as $index=>$teacher): ?><tr><td style="text-align:center"><?= $index+1 ?></td><td><?= esc($teacher['full_name']) ?></td><td><?= esc($teacher['identifier']) ?></td><td><?php foreach($teacher['assignments'] as $a): ?><?= esc($a['subject_name'].' · '.$a['classroom_name'].' ('.number_format((float)$a['assigned_weekly_hours'],1).' JP)') ?><br><?php endforeach; ?></td><td><?php foreach($teacher['duties'] as $d): ?><?= esc($d['duty_name']) ?><br><?php endforeach; ?></td><td style="text-align:center"><?= number_format($teacher['teaching_hours'],1) ?></td><td style="text-align:center"><?= number_format($teacher['duty_hours'],1) ?></td><td style="text-align:center"><strong><?= number_format($teacher['total_hours'],1) ?></strong></td></tr><?php endforeach; ?>
</tbody></table></body></html>
