<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#7657eb"><title>Surat Tugas Guru</title>
<style>
*{box-sizing:border-box}body{font:13px "Times New Roman",serif;color:#000;margin:22mm}.toolbar{position:sticky;top:10px;z-index:2;display:flex;justify-content:flex-end;gap:8px}.toolbar a,.toolbar button{font:700 14px Arial;padding:9px 16px;border:1px solid #d9d5e9;border-radius:10px;text-decoration:none}.toolbar a{color:#5745c9;background:#fff}.toolbar button{color:#fff;background:#7657eb;border-color:#7657eb}.document-page{max-width:190mm;margin:0 auto 18mm}.document-page+.document-page{padding-top:18mm;border-top:1px dashed #aaa}.preview{font:700 13px Arial;color:#8a5700;background:#fff3cd;border:1px solid #ffe69c;padding:10px 14px;margin:0 0 16px;text-align:center}.header{text-align:center;border-bottom:3px double #000;padding-bottom:10px}.header h2,.header p{margin:3px}.title{text-align:center;margin:24px 0}.content{line-height:1.6}table{width:100%;border-collapse:collapse;margin:14px 0}th,td{border:1px solid #000;padding:7px}.signature{width:42%;margin:32px 0 0 auto}
@media screen and (max-width:767px){body{margin:0;padding:calc(10px + env(safe-area-inset-top,0px)) 10px 24px;background:#f4f3fb}.toolbar{top:8px;margin-bottom:10px;padding:8px;border:1px solid #e4e0f2;border-radius:18px;background:rgba(255,255,255,.94);box-shadow:0 12px 30px rgba(47,38,89,.12);backdrop-filter:blur(16px)}.toolbar a,.toolbar button{min-height:42px;display:inline-flex;align-items:center;justify-content:center}.document-page{max-width:none;overflow-x:auto;margin:0 0 16px;padding:18px 14px;border:1px solid #e4e0f2;border-radius:20px;background:#fff;box-shadow:0 12px 34px rgba(47,38,89,.08)}.preview{border-radius:12px;font-size:11px}.header h2{font-size:17px}.title{margin:19px 0}.content table{min-width:650px}.signature{min-width:210px;width:55%}}
@media print{.toolbar{display:none}.document-page{max-width:none;margin:0;break-after:page}.document-page:last-child{break-after:auto}.document-page+.document-page{padding-top:0;border:0}.preview{border:2px solid #000;color:#000;background:#fff}body{margin:0}@page{size:A4 portrait;margin:18mm}}
</style></head><body>
<?php $documents = $documents ?? [$document]; ?>
<div class="toolbar"><a href="<?= base_url('dashboard') ?>">Kembali</a><button type="button" onclick="window.print()"><?= !empty($isOfficial) ? 'Cetak / Simpan PDF' : 'Cetak Pratinjau' ?></button></div>
<?php foreach ($documents as $documentIndex => $document): $unit=$document['unit'];$version=$document['version'];$teacher=$document['teachers'][0];$documentOfficial=(bool)($document['is_official'] ?? $isOfficial ?? false); ?>
<section class="document-page">
<?php if (!$documentOfficial): ?><div class="preview">PRATINJAU &mdash; BELUM MERUPAKAN SK RESMI (STATUS: <?= esc($version['workflow_status']) ?>)</div><?php endif; ?>
<div class="header"><h2><?= esc(strtoupper($unit['name'])) ?></h2><p><?= esc($unit['address'] ?: '') ?></p></div>
<div class="title"><h3><u>SURAT TUGAS MENGAJAR</u></h3><p>Turunan dari SK Nomor: <?= esc($document['document_number']) ?></p></div>
<div class="content"><p>Kepala <?= esc($unit['name']) ?> menugaskan kepada:</p><p><strong>Nama:</strong> <?= esc($teacher['full_name']) ?><br><strong>NIP/Nomor Pegawai:</strong> <?= esc($teacher['identifier']) ?></p><p>untuk melaksanakan tugas mengajar dan tugas tambahan pada <?= esc($version['period_name'].' Tahun Pelajaran '.$version['year_name']) ?> sebagai berikut:</p>
<table><thead><tr><th>No</th><th>Mata Pelajaran</th><th>Kelas</th><th>Alokasi JP/Minggu</th><th>Beban Diakui</th></tr></thead><tbody><?php foreach($teacher['assignments'] as $i=>$a): ?><tr><td><?= $i+1 ?></td><td><?= esc($a['subject_name']) ?></td><td><?= esc($a['classroom_name']) ?></td><td><?= number_format((float)$a['assigned_weekly_hours'],1) ?></td><td><?= number_format((float)$a['workload_weekly_hours'],1) ?></td></tr><?php endforeach; ?><tr><th colspan="3">Total</th><th><?= number_format((float)($teacher['assigned_hours'] ?? 0),1) ?></th><th><?= number_format((float)$teacher['teaching_hours'],1) ?></th></tr></tbody></table>
<?php if($teacher['duties']): ?><p><strong>Tugas tambahan:</strong> <?php foreach($teacher['duties'] as $d): ?><?= esc($d['duty_name'].' ('.number_format((float)$d['workload_hours'],1).' JP)') ?>; <?php endforeach; ?></p><?php endif; ?>
<p>Surat tugas ini dilaksanakan dengan penuh tanggung jawab dan dipergunakan sebagaimana mestinya.</p></div>
<div class="signature"><?= esc($unit['document_city'] ?: '................') ?>, <?= date('d-m-Y',strtotime($document['issued_date'])) ?><br>Kepala Sekolah,<br><br><br><strong><u><?= esc($unit['head_name'] ?: '................................') ?></u></strong><br><?= $unit['head_identifier'] ? 'NIP/Identitas: '.esc($unit['head_identifier']) : '' ?></div>
</section>
<?php endforeach; ?>
</body></html>
