<?= $this->extend('layouts/admin') ?><?= $this->section('main_content') ?>
<?= view('ksp/_header', compact('version')) ?>
<div class="row g-4"><div class="col-xl-8"><div class="card border-0 shadow-sm rounded-4"><div class="card-body p-4"><div class="d-flex justify-content-between mb-2"><h5 class="fw-bold">Kesiapan dokumen</h5><strong><?= (int)$readiness['overall'] ?>%</strong></div><div class="progress mb-4" style="height:10px"><div class="progress-bar" style="width:<?= (int)$readiness['overall'] ?>%"></div></div><div class="row g-3">
<?php foreach($sections as $section): ?><div class="col-md-6"><div class="border rounded-3 p-3 h-100"><div class="d-flex justify-content-between"><span class="fw-semibold"><?= esc(str_replace('_',' ',ucwords(strtolower($section['section_code'])))) ?></span><span><?= (int)$section['completion_percent'] ?>%</span></div><small class="text-muted"><?= esc($section['status']) ?></small><?php if($canManage): ?><form class="row g-2 mt-2" method="post" action="<?= base_url('education/ksp/'.$version['uuid'].'/sections/'.$section['section_code']) ?>"><?= csrf_field() ?><input type="hidden" name="revision_number" value="<?= $section['revision_number'] ?>"><div class="col-4"><input class="form-control form-control-sm" type="number" min="0" max="100" name="completion_percent" value="<?= $section['completion_percent'] ?>" aria-label="Persentase"></div><div class="col-5"><input class="form-control form-control-sm" name="notes" value="<?= esc($section['notes'] ?? '') ?>" placeholder="Catatan/bukti"></div><div class="col-3"><button class="btn btn-sm btn-outline-primary w-100">Simpan</button></div></form><?php endif ?></div></div><?php endforeach ?>
</div></div></div></div><div class="col-xl-4"><div class="card border-0 shadow-sm rounded-4"><div class="card-body"><h5 class="fw-bold">Workflow persetujuan</h5><p class="small text-muted">Pengajuan review memerlukan kesiapan minimal 75%. Dokumen yang disetujui atau dikunci tidak dapat diubah.</p>
<?php $targets=['DRAFT'=>['REVIEW','Ajukan review'],'REVIEW'=>['APPROVED','Setujui KSP'],'APPROVED'=>['LOCKED','Kunci KSP'],'LOCKED'=>['SUPERSEDED','Supersede']]; $allowed=['REVIEW'=>'ksp.review','APPROVED'=>'ksp.approve','LOCKED'=>'ksp.lock','SUPERSEDED'=>'ksp.lock']; ?>
<?php if(isset($targets[$version['status']])): [$target,$label]=$targets[$version['status']]; if(has_permission($allowed[$target])): ?><form method="post" action="<?= base_url('education/ksp/'.$version['uuid'].'/transition') ?>"><?= csrf_field() ?><input type="hidden" name="target_status" value="<?= $target ?>"><input type="hidden" name="revision_number" value="<?= $version['revision_number'] ?>"><button class="btn btn-primary w-100"><?= $label ?></button></form><?php endif; endif ?>
<?php if($version['status']==='REVIEW' && has_permission('ksp.review')): ?><form class="mt-2" method="post" action="<?= base_url('education/ksp/'.$version['uuid'].'/transition') ?>"><?= csrf_field() ?><input type="hidden" name="target_status" value="DRAFT"><input type="hidden" name="revision_number" value="<?= $version['revision_number'] ?>"><button class="btn btn-outline-secondary w-100">Kembalikan ke draft</button></form><?php endif ?>
</div></div></div></div>
<?= $this->endSection() ?>
