<?= $this->extend('layouts/admin') ?>
<?= $this->section('main_content') ?>
<?php
$statuses = [
    'HADIR'=>['H','success','Hadir'], 'TERLAMBAT'=>['T','warning','Terlambat'],
    'IZIN'=>['I','info','Izin'], 'SAKIT'=>['S','primary','Sakit'],
    'ALPA'=>['A','danger','Alpa'], 'DISPENSASI'=>['D','secondary','Dispensasi'],
];
$isSubject = $sessionType === 'SUBJECT';
?>
<style>
.attendance-form-app{max-width:1050px;margin:auto}.form-hero{background:linear-gradient(135deg,#2e1f69,#6d43ec);color:#fff;border-radius:1.4rem}.student-row{border:1px solid #e9eaf0;border-radius:1rem;background:#fff}.status-chip label{min-width:40px;border-radius:.7rem!important}.student-extra{display:grid;grid-template-columns:120px 90px 1fr;gap:.5rem}.sticky-save{position:sticky;bottom:.75rem;z-index:9;background:rgba(255,255,255,.92);backdrop-filter:blur(14px);border:1px solid #e7e8ef;border-radius:1rem;padding:.65rem;box-shadow:0 .8rem 2rem rgba(36,24,70,.14)}@media(max-width:767.98px){.attendance-form-app{padding:0 .25rem 6rem}.form-hero{margin:-1rem -.75rem 1rem;border-radius:0 0 1.5rem 1.5rem}.desktop-head{display:none}.student-row{padding:1rem!important}.status-chip{display:grid!important;grid-template-columns:repeat(6,1fr);width:100%}.status-chip label{padding:.45rem .2rem!important;font-size:.75rem}.student-extra{grid-template-columns:1fr 90px}.student-extra .notes{grid-column:1/-1}.sticky-save{bottom:5rem}.journal-tabs textarea{min-height:90px}}
</style>
<div class="container-fluid py-3 attendance-form-app">
    <section class="form-hero p-4 mb-3">
        <a href="<?= base_url('portal/attendance?date='.urlencode($date)) ?>" class="text-white text-decoration-none small"><i data-lucide="arrow-left" class="icon-xs me-1"></i>Kembali</a>
        <div class="d-flex justify-content-between align-items-start gap-3 mt-3"><div><span class="badge bg-white bg-opacity-20 text-white mb-2"><?= esc($sessionTypeLabel) ?></span><h2 class="fw-bold text-white mb-1"><?= esc($classroom['name'] ?? 'Pilih kegiatan') ?></h2><p class="mb-0 text-white text-opacity-75"><?= esc($subject['name'] ?? ($session['topic'] ?? $sessionTypeLabel)) ?> · <?= date('d M Y',strtotime($date)) ?></p></div><?php if($session):?><span class="badge bg-white text-primary rounded-pill px-3 py-2"><?= esc($session['status']) ?></span><?php endif;?></div>
    </section>
    <?php foreach(['success'=>'success','error'=>'danger'] as $key=>$tone):if(session()->getFlashdata($key)):?><div class="alert alert-<?= $tone ?> border-0 rounded-4"><?= esc(session()->getFlashdata($key)) ?></div><?php endif;endforeach;?>

    <?php if(!$classroom): ?>
        <div class="card border-0 shadow-sm rounded-4"><div class="card-body p-4"><h5 class="fw-bold">Pilih penugasan</h5><p class="text-muted">Mulai dari timeline harian agar sesi otomatis terhubung dengan jadwal. Untuk input manual, pilih penugasan berikut.</p><div class="d-grid gap-2"><?php foreach($teachingAssignments as $assignment):?><a class="btn btn-light border text-start p-3" href="?type=SUBJECT&date=<?= urlencode($date) ?>&classroom_id=<?= $assignment['classroom_id'] ?>&subject_id=<?= $assignment['subject_id'] ?>"><strong><?= esc($assignment['subject_name']) ?></strong><small class="d-block text-muted"><?= esc($assignment['classroom_name']) ?> · <?= esc($assignment['unit_name']) ?></small></a><?php endforeach;?></div></div></div>
    <?php else: ?>
    <?php if($isLocked):?><div class="alert alert-success rounded-4 border-0"><i data-lucide="lock" class="icon-sm me-2"></i>Sesi telah diverifikasi dan dikunci. Data ditampilkan dalam mode baca-saja.</div><?php endif;?>
    <form action="<?= base_url('portal/attendance/save') ?>" method="post" id="attendanceForm">
        <?= csrf_field() ?>
        <input type="hidden" name="session_id" value="<?= esc($session['id']??'') ?>"><input type="hidden" name="revision_number" value="<?= (int)($session['revision_number']??0) ?>">
        <input type="hidden" name="session_type" value="<?= esc($sessionType) ?>"><input type="hidden" name="source_key" value="<?= esc($sourceKey) ?>"><input type="hidden" name="schedule_entry_id" value="<?= (int)$scheduleEntryId ?>">
        <input type="hidden" name="classroom_id" value="<?= (int)$classroomId ?>"><input type="hidden" name="subject_id" value="<?= (int)$subjectId ?>">
        <fieldset <?= $isLocked?'disabled':'' ?>>
        <div class="card border-0 shadow-sm rounded-4 mb-3"><div class="card-body p-4"><div class="row g-3"><div class="col-sm-4"><label class="form-label fw-semibold">Tanggal</label><input type="date" class="form-control" name="attendance_date" value="<?= esc($date) ?>" min="<?= esc($activePeriod['start_date']) ?>" max="<?= esc($activePeriod['end_date']) ?>" <?= $session?'readonly':'' ?> required></div><div class="col-sm-4"><label class="form-label fw-semibold">Pertemuan</label><input type="number" class="form-control" name="meeting_number" min="1" max="100" value="<?= (int)$meetingNum ?>" required></div><div class="col-sm-4"><label class="form-label fw-semibold">Sumber</label><div class="form-control bg-light text-muted"><?= $scheduleEntryId?'Jadwal resmi':'Tugas kelas/guru' ?></div></div><div class="col-12"><label class="form-label fw-semibold"><?= $isSubject?'Topik/Pokok Bahasan':'Nama kegiatan' ?></label><input class="form-control" name="topic" maxlength="255" value="<?= esc($session['topic']??($isSubject?'':$sessionTypeLabel)) ?>" required></div></div></div></div>

        <div class="row g-2 mb-3" id="attendanceCounters"><?php foreach($statuses as $code=>[$short,$tone,$label]):?><div class="col-4 col-md-2"><div class="bg-<?= $tone ?>-subtle rounded-4 p-2 text-center"><small class="fw-bold text-<?= $tone ?>"><?= $short ?> · <?= $label ?></small><strong class="d-block fs-4 text-<?= $tone ?>" data-counter="<?= $code ?>"><?= (int)($counts[$code]??0) ?></strong></div></div><?php endforeach;?></div>

        <div class="card border-0 shadow-sm rounded-4 mb-3"><div class="card-header bg-white border-0 p-4 d-flex flex-wrap justify-content-between gap-2"><div><h5 class="fw-bold mb-0">Kehadiran siswa</h5><small class="text-muted"><?= count($roster) ?> siswa · ketuk status untuk mengubah</small></div><div class="d-flex gap-2"><button type="button" class="btn btn-sm btn-outline-success rounded-pill" data-set-all="HADIR">Semua hadir</button><input id="studentSearch" class="form-control form-control-sm" placeholder="Cari siswa…" style="max-width:150px"></div></div><div class="card-body p-3 p-md-4 d-grid gap-2">
            <?php foreach($roster as $index=>$student):$studentId=(int)$student['student_id'];$current=strtoupper((string)($student['status']??'HADIR'));?>
            <article class="student-row p-3" data-student-name="<?= esc(strtolower($student['full_name']),'attr') ?>"><div class="d-flex align-items-start gap-3 mb-3"><div class="rounded-circle bg-primary-subtle text-primary fw-bold d-grid place-items-center" style="width:38px;height:38px;place-items:center"><?= $index+1 ?></div><div class="flex-grow-1 min-w-0"><strong class="d-block text-truncate"><?= esc($student['full_name']) ?></strong><small class="text-muted"><?= esc($student['student_number']) ?></small><?php if(!empty($student['source_session_id'])):?><span class="badge bg-warning-subtle text-warning-emphasis ms-2">Saran sesi sebelumnya</span><?php endif;?></div></div>
                <div class="btn-group status-chip d-flex mb-2" role="group"><?php foreach($statuses as $code=>[$short,$tone,$label]):$id='status_'.$studentId.'_'.$code;?><input class="btn-check status-radio" type="radio" name="roster[<?= $studentId ?>][status]" id="<?= $id ?>" value="<?= $code ?>" <?= $current===$code?'checked':'' ?>><label class="btn btn-outline-<?= $tone ?>" for="<?= $id ?>" title="<?= $label ?>"><?= $short ?></label><?php endforeach;?></div>
                <div class="student-extra"><input type="time" class="form-control form-control-sm arrival" name="roster[<?= $studentId ?>][arrival_time]" value="<?= esc($student['arrival_time']??'') ?>" aria-label="Jam datang"><input type="number" min="0" max="600" class="form-control form-control-sm late-minutes" name="roster[<?= $studentId ?>][late_minutes]" value="<?= (int)($student['late_minutes']??0) ?>" placeholder="Menit"><input class="form-control form-control-sm notes" maxlength="255" name="roster[<?= $studentId ?>][notes]" value="<?= esc($student['notes']??'') ?>" placeholder="Catatan/alasan"><input type="hidden" name="roster[<?= $studentId ?>][source_session_id]" value="<?= (int)($student['source_session_id']??0) ?>"></div>
            </article><?php endforeach;?>
        </div></div>

        <div class="card border-0 shadow-sm rounded-4 mb-3"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><span class="section-label text-primary fw-bold small">JURNAL</span><h5 class="fw-bold mb-0"><?= $isSubject?'Jurnal pembelajaran':'Catatan kegiatan' ?></h5></div><i data-lucide="notebook-pen" class="text-primary"></i></div><?php if($isSubject):?><div class="row g-3 journal-tabs"><div class="col-md-6"><label class="form-label fw-semibold">Tujuan pembelajaran</label><textarea class="form-control" name="learning_objectives" rows="3" placeholder="Kompetensi/tujuan yang dicapai…"><?= esc($session['learning_objectives']??'') ?></textarea></div><div class="col-md-6"><label class="form-label fw-semibold">Aktivitas pembelajaran</label><textarea class="form-control" name="learning_activity" rows="3" placeholder="Pendahuluan, inti, penutup…"><?= esc($session['learning_activity']??'') ?></textarea></div><div class="col-md-6"><label class="form-label fw-semibold">Asesmen & capaian</label><textarea class="form-control" name="assessment_summary" rows="3" placeholder="Bentuk asesmen dan ringkasan hasil…"><?= esc($session['assessment_summary']??'') ?></textarea></div><div class="col-md-6"><label class="form-label fw-semibold">Tindak lanjut</label><textarea class="form-control" name="follow_up" rows="3" placeholder="Remedial, pengayaan, tugas…"><?= esc($session['follow_up']??'') ?></textarea></div></div><?php endif;?><label class="form-label fw-semibold mt-3">Catatan/kendala</label><textarea class="form-control" name="teaching_summary" rows="3" placeholder="Catatan penting, kendala, kejadian kelas…"><?= esc($session['teaching_summary']??'') ?></textarea></div></div>

        <?php if(!$isLocked):?><div class="sticky-save d-flex gap-2"><button class="btn btn-light flex-grow-1" name="submit_action" value="draft"><i data-lucide="save" class="icon-xs me-1"></i>Simpan Draft</button><button class="btn btn-primary flex-grow-1" name="submit_action" value="submit"><i data-lucide="send" class="icon-xs me-1"></i>Kirim Presensi</button></div><?php endif;?>
        </fieldset>
    </form>
    <?php if($session):?><div class="d-flex justify-content-center gap-2 mt-3"><a class="btn btn-outline-secondary" target="_blank" href="<?= base_url('portal/attendance/session/'.$session['id'].'/print') ?>"><i data-lucide="printer" class="icon-xs me-1"></i>Cetak</a><?php if(!$isLocked):?><form method="post" action="<?= base_url('portal/attendance/session/'.$session['id'].'/delete') ?>" onsubmit="return confirm('Arsipkan sesi ini?')"><?= csrf_field() ?><button class="btn btn-outline-danger">Arsipkan</button></form><?php endif;?></div><?php endif;?>
    <?php endif; ?>
</div>
<script>
const updateCounters=()=>{document.querySelectorAll('[data-counter]').forEach(el=>el.textContent=document.querySelectorAll('.status-radio:checked[value="'+el.dataset.counter+'"]').length)};
document.querySelectorAll('.status-radio').forEach(r=>r.addEventListener('change',()=>{const row=r.closest('.student-row');const late=r.value==='TERLAMBAT';row.querySelector('.late-minutes').disabled=!late;if(!late)row.querySelector('.late-minutes').value=0;updateCounters()}));
document.querySelector('[data-set-all]')?.addEventListener('click',e=>{document.querySelectorAll('.status-radio[value="'+e.currentTarget.dataset.setAll+'"]').forEach(r=>{r.checked=true;r.dispatchEvent(new Event('change'))})});
document.getElementById('studentSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('[data-student-name]').forEach(row=>row.hidden=!row.dataset.studentName.includes(q))});
document.querySelectorAll('.status-radio:checked').forEach(r=>r.dispatchEvent(new Event('change')));
</script>
<?= $this->endSection() ?>
